# fly.toml app configuration file generated for recipe-book-holy-dew-1625 on 2026-04-15T14:16:05+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'recipe-book-holy-dew-1625'
primary_region = 'sin'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.health]
    port = 3000
    type = 'http'
    interval = '30s'
    timeout = '5s'
    path = '/api/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
